name: CI
on:
  push:
    branches:
      - main
    tags:
      - "!*"
    paths-ignore:
      - "**.md"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
          cache: true
      - name: Get dependencies
        run: |
          make install
      - name: Run test
        run: |
          make test
      - name: Check for build ability
        run: |
          go build -v ./main.go

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
          cache: true
      - name: Get dependencies
        run: |
          make tools
      - name: Run lint
        run: |
          make lint

  deploy:
    needs:
      - test
      - lint
    if: contains(github.ref, 'main')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.RENDER_COM_DEPLOY_HOOK_URL }}
          method: 'GET'
